# Utilise une image Python légère
FROM python:3.11-slim

# Définir le répertoire de travail dans le container
WORKDIR /app

# Copier le contenu du dossier "project" dans /app
COPY project/ /app/

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port (pour information)
EXPOSE 8000

# Démarrer l’application
CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]