# Utilise une image légère de Python
FROM python:3.11-slim

# Crée un dossier de travail
WORKDIR /app

# Copie les fichiers de dépendances
COPY requirements.txt .

# Installe les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copie tout le code
COPY project/ /app/
WORKDIR /app 

# Expose le port utilisé par Uvicorn
EXPOSE 8000

# Lance l’application FastAPI
CMD ["python", "main.py"]